language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

cache:
  - pip

install:
  - pip install -U pip tox tox-travis coveralls codecov

script:
  - tox

after_success:
  - codecov
